title: Scientist Poems
email: scientistpoems@nvx.li
description: Apenas os momentos onde meu sentimento é forte demais e preciso escrever ele.
baseurl: ""
url: "https://scientistpoems.lucasteske.dev"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

paginate: 5

minima:
  social_links:
    twitter: lucasteske
    github: racerxdl
    facebook: elenic.racerxdl
    flickr: energylabs
    instagram: racerxdl
    telegram: lucasteske
    keybase: racerxdl
