title: Scientist Poems
email: scientistpoems@nvx.li
description: Apenas os momentos onde meu sentimento é forte demais e preciso escrever ele.
baseurl: ""
url: "https://scientistpoems.lucasteske.dev"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

paginate: 5

# Google Analytics
google_analytics: UA-34023969-2

minima:
  social_links:
    twitter: lucasteske
    github: racerxdl
    facebook: elenic.racerxdl
    flickr: energylabs
    instagram: racerxdl
    telegram: lucasteske
    keybase: racerxdl
    youtube_channel: TeskesLab

twitter:
  username: lucasteske
  card: summary_large_image

facebook:
  app_id: 1209208119176770
  publisher: https://www.facebook.com/teskeslab
  admins: 1234

social:
  name: Lucas Teske
  links:
    - https://twitter.com/lucasteske
    - https://www.facebook.com/elenic.racerxdl
    - https://instagram.com/racerxdl/
    - https://github.com/racerxdl
    - https://keybase.io/racerxdl
    - https://www.linkedin.com/in/lucas-teske-8206301b/
    - https://www.youtube.com/c/TeskesLab